apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-matrix
spec:
  params:
    - name: message
      type: string
      description: "The message to send to the Matrix room"
  tasks:
    - name: notify-matrix-room
      params:
        - name: message
          value: $(params.message)
      taskRef:
        kind: Task
        name: notification-to-matrix